name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "⬆️ Dependencies"
    labels:
      - "dependencies"
change-template: "- $TITLE (#$NUMBER) [@$AUTHOR]"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

exclude-labels:
  - 'changelog-ignore'
  - 'github_actions'

autolabeler:
  - label: 'changelog-ignore'
    title:
      - '/chore[(]\s*deps-dev\s*[)]\s*[:].*/i'

template: |
  ## New in scan-action v$RESOLVED_VERSION

  $CHANGES
