name: 'anchore-scan'
description: 'Scan a docker container, including vulnerabilities, and perform policy evaluation optionally failing build'
branding:
  color: blue
  icon: check-circle
inputs:
  image-reference:
    description: 'The image to scan'
    required: true
  dockerfile-path:
    description: 'Path to the dockerfile'
    required: false
  debug:
    description: 'Set this to any value to enable verbose debug output'
    required: false
  fail-build:
    description: 'Set to any value to cause build to fail upon failed anchore policy evaluation'
    required: false
  include-app-packages:
    description: 'Set to true to include software packages during vulnerability scanning - this option will increase runtime of the action significantly. By default only OS packages are scanned for vulnerabilities.'
  custom-policy-path:
    description: 'Path to a custom policy json file. See https://docs.anchore.com/current/docs/engine/general/concepts/policy/bundles/ for information on building bundles'
    required: false
outputs:
  billofmaterials:
    description: 'The json output report specifying the content of the image'
  vulnerabilities:
    description: 'The found vulnerabilities for the image'
  policycheck:
    descrption: 'The json report for evaluating the image against the given policy, if present'
runs:
  using: 'node12'
  main: 'dist/index.js'
